### ISSUE TITLE
Define auth property for the redirect route

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hapi-auth-google#11]
At the moment we don't precise if the [redirect route](https://github.com/dwyl/hapi-auth-google/blob/b3083d172d793ceebc277a0ac629ab65def686f6/lib/index.js#L44-L65) need to be accessible with authentication. It can be a problem if the plugin is used with an authentication purpose

**Comment by nelsonic** [comment]
Thanks for doing this. :+1:
