### ISSUE TITLE
Hoek needs to be put in the dependencies instead of dev dependencies. 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hapi-auth-google#13]
It is being required in the main index.js file. 

https://github.com/dwyl/hapi-auth-google/blob/61757638824623405a70e199b0a40dda9d919d87/lib/index.js#L4

When I run travis in one of the other projects the build is failing due to it requiring hoek.

**Comment by nelsonic** [comment]
@sohilpandya thanks for reporting this. :+1: 
(_next time feel free to PR the fix..._ :wink:  )
