### ISSUE TITLE
Get refresh token

### ISSUE THREAD

**Issue by heron2014** [dwyl/hapi-auth-google#20]
Its good to store refresh token for future use when application receive it in a first place, because if an application loses the refresh token, it will have to re-prompt the user for consent before obtaining another refresh token. To avoid re-prompt the user to consent we can include the parameter: 

`approval_prompt: 'force'`

in the authorization code request.

**Comment by nelsonic** [comment]
@heron2014 can you please share a link to where this is documented in the Google API/Docs?

**Comment by heron2014** [comment]
@nelsonic [Google API Docs](https://developers.google.com/gmail/api/auth/web-server).

**Comment by nelsonic** [comment]
this was merged in. so is considered fixed.
