### ISSUE TITLE
Pass route config object with options

### ISSUE THREAD

**Issue by Y-LyN-10** [dwyl/hapi-auth-google#38]
Hey, thank you for this amazing plugin and detailed readme. I appreciate your work! 

I thought that it would be great if we could pass optional config object to the google auth callback route. 
It might be needed when building a documentation or enhancing the logs, for example.

```javascript
config: {
    description: 'Google auth callback',
    notes: 'Handled by hapi-auth-google plugin',
    tags: ['api', 'auth', 'plugin']
}
```

**Comment by nelsonic** [comment]
@Y-LyN-10 great point! 🤔 
We'd be delighted to get a _backward-compatible_ enhancement Pull Request for this feature. 👍

**Comment by Y-LyN-10** [comment]
Awesome, @nelsonic! You can assign me for that :)

**Comment by nelsonic** [comment]
@Y-LyN-10 all yours. please assign PR to me. thanks! 👍 
p.s. you have write access to the repo. so please create a branch in the dwyl (_rather than forking_)

**Comment by nelsonic** [comment]
Version **16.1.0** of `hapi-auth-google` now contains this feature improvement thanks to @Y-LyN-10 🚀
