### ISSUE TITLE
Do we need Multiple Scopes?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-google#4]
At present we have _hard-coded_ the scope for the plugin.
see: https://github.com/dwyl/hapi-auth-google/blob/9df5f9f25485ee26fed35613b8dc4af1d7db8e00/lib/index.js#L34
@SimonLab + @heron2014 do we need the ability to define a **_custom scope**_ for the Project?

**Comment by nelsonic** [comment]
What are some examples of scopes people can ask for?

**Comment by SimonLab** [comment]
People might want to read and write some emails. The scope _https://www.googleapis.com/auth/gmail.compose_ is needed for this.
See gmail scopes [here](https://developers.google.com/gmail/api/auth/scopes)

**Comment by nelsonic** [comment]
@SimonLab please see last commit. :+1:

**Comment by nelsonic** [comment]
This was added in v1.0.5 so closing this PR.
