### ISSUE TITLE
Empty link GOOGLE-APP-STEP-BY-STEP-GUIDE 

### ISSUE THREAD

**Issue by heron2014** [dwyl/hapi-auth-google#9]
Links redirect to 404 Page if I click on both GOOGLE-APP-STEP-BY-STEP-GUIDE links  in README file
![google_steps](https://cloud.githubusercontent.com/assets/8476884/11209808/8115e65c-8d1b-11e5-83c2-94bed5befedf.png)

**Comment by nelsonic** [comment]
OOps... please update to: https://github.com/dwyl/hapi-auth-google/blob/master/GOOGLE-APP-STEP-BY-STEP-GUIDE.md thanks :+1:

**Comment by iteles** [comment]
@heron2014 Merged! Feel free to close this issue :blush:

**Comment by heron2014** [comment]
:+1:
